version: '3'

services:
  zookeeper1:
    image: wurstmeister/zookeeper
    hostname: zookeeper1
    container_name: zookeeper1
    ports:
      - "2181:2181"
    volumes:
       - "/home/u/fabric/zookeeper/zoo/data:/data"
       - "/home/u/fabric/zookeeper/zoo/datalog:/datalog"
  kafka1:
    image: wurstmeister/kafka
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
    volumes:
       - "/home/u/fabric/kafka/kafka/logs:/kafka1"
    external_links:
    - zookeeper1
